import { Target, Sparkles, Puzzle, Zap, Palette, Database } from "lucide-react"
import type { Project } from "@/types"

export const projects: Project[] = [
  {
    title: "Math Escape",
    description: "Dungeon escape game where players solve math problems to progress through levels",
    tech: ["Unity 3D", "C#", "Level Design", "3D Movement"],
    features: ["3D dungeon environments", "Educational math integration", "Progressive difficulty"],
    status: "Completed",
    type: "Professional",
    icon: Target,
    gradient: "from-primary to-secondary",
  },
  {
    title: "Jingle Word",
    description: "Word-making game with leaderboard system and monetization features",
    tech: ["Unity", "C#", "AdMob", "UI Design"],
    features: ["Leaderboard system", "User authentication", "AdMob integration"],
    status: "Completed",
    type: "Professional",
    icon: Sparkles,
    gradient: "from-secondary to-primary",
  },
  {
    title: "Sudoku Game",
    description: "Multiplayer 2D Sudoku game with dynamic UI and real-time gameplay",
    tech: ["Unity", "C#", "Multiplayer", "UI"],
    features: ["9x9 grid layout", "Real-time multiplayer", "Dynamic difficulty"],
    status: "In Development",
    type: "Personal",
    icon: Puzzle,
    gradient: "from-primary/80 to-secondary/80",
  },
  {
    title: "Atomic Architect",
    description: "Educational game focused on atomic structure assembly and chemistry learning",
    tech: ["Unity", "C#", "Scriptable Objects", "Touch Controls"],
    features: ["Interactive particles", "Scalable data management", "Progressive learning"],
    status: "Completed",
    type: "Educational",
    icon: Zap,
    gradient: "from-secondary to-primary",
    link: "https://towhid-01.itch.io/atomic-architect",
  },
  {
    title: "Order Up",
    description: "Educational alphabet sorting game designed for children",
    tech: ["Unity", "C#", "DOTween", "Children's UI"],
    features: ["Alphabet sorting gameplay", "Smooth animations", "Child-friendly design"],
    status: "Completed",
    type: "Educational",
    icon: Palette,
    gradient: "from-primary to-secondary",
  },
  {
    title: "File Manager",
    description: "Console-based file management system with robust error handling",
    tech: ["C#", "OOP", "Console App", "Error Handling"],
    features: ["Core file operations", "Modular design", "Scalable architecture"],
    status: "Completed",
    type: "Utility",
    icon: Database,
    gradient: "from-secondary/80 to-primary/80",
  },
]
